"""Materia Arcana — Planetas clásicos, signos zodiacales y ángeles/espíritus planetarios.
Fuentes: Agrippa Lib. II & III, Golden Dawn *777*, tradición hermética.
"""

PLANETAS: list[dict] = [
    dict(slug="planeta-sol", item_type="planet", name="Sol", planet="sun", element="fuego",
         aliases=["Sun", "Helios", "Shamash", "☉"],
         properties={
             "intenciones": ["éxito", "vitalidad", "autoridad", "salud", "iluminación"],
             "notas": "El planeta de la voluntad consciente, la identidad y el poder soberano.",
             "estudio": "El Sol rige el corazón, los ojos y el espíritu vital (pneuma). Agrippa (Lib. II) le asigna el número 6, el cuadrado planetario de 6×6 (suma 111), el día domingo, el color dorado/amarillo, el metal oro, el ángel Miguel, la inteligencia Nakhiel y el espíritu Sorath. Sus hierbas incluyen olíbano, laurel, romero, hipérico y caléndula. En la cábala corresponde a Tiphareth (Sephirah 6, la Belleza). El sol surge como símbolo de la consciencia individuada en psicología jungiana — el Yo solar.",
             "dia": "domingo",
             "metal": "oro",
             "color": "dorado / amarillo",
             "numero": "6",
             "angel_regente": "Miguel",
             "inteligencia": "Nakhiel",
             "espiritu": "Sorath",
             "sephirah": "Tiphareth (6)",
             "fuente": "Agrippa, Lib. II cap. XXII; Golden Dawn, 777; Cábala (Sepher Yetzirah)",
         }),

    dict(slug="planeta-luna", item_type="planet", name="Luna", planet="moon", element="agua",
         aliases=["Moon", "Selene", "Hécate", "☽"],
         properties={
             "intenciones": ["intuición", "ciclos", "sueños", "psiquismo", "mareas"],
             "notas": "La Luna rige el inconsciente, los fluidos, los ritmos biológicos y la magia receptiva.",
             "estudio": "La Luna rige los fluidos del cuerpo, el cerebro (parte inferior), el útero y el sistema reproductivo femenino. Agrippa (Lib. II) le asigna el número 9, el cuadrado planetario de 9×9, el día lunes, el color plateado/blanco, el metal plata, el ángel Gabriel, la inteligencia Malkah Be-Tarshishim y el espíritu Hasmodai. Sus hierbas incluyen artemisa, sauce, malva, nenúfar y cálamo. En cábala corresponde a Yesod (Sephirah 9, el Fundamento). Las fases lunares estructuran el tiempo ritual: luna nueva (inicio), llena (plenitud), menguante (retiro).",
             "dia": "lunes",
             "metal": "plata",
             "color": "plateado / blanco",
             "numero": "9",
             "angel_regente": "Gabriel",
             "inteligencia": "Malkah Be-Tarshishim",
             "espiritu": "Hasmodai",
             "sephirah": "Yesod (9)",
             "fuente": "Agrippa, Lib. II cap. XXIV; Golden Dawn, 777; Cábala (Sepher Yetzirah)",
         }),

    dict(slug="planeta-mercurio", item_type="planet", name="Mercurio", planet="mercury", element="aire",
         aliases=["Mercury", "Hermes", "Thoth", "☿"],
         properties={
             "intenciones": ["comunicación", "inteligencia", "comercio", "magia", "viaje"],
             "notas": "El mensajero entre mundos; rige la mente, el lenguaje y la transmisión de todo conocimiento.",
             "estudio": "Mercurio rige los pulmones, el sistema nervioso, los sentidos y la capacidad de lenguaje. Agrippa (Lib. II) le asigna el número 8, el cuadrado de 8×8, el día miércoles, color naranja/mezclado, metal azogue (mercurio), ángel Rafael, inteligencia Tiriel y espíritu Tapthartharath. Sus hierbas incluyen valeriana, menta, mandrágora, eneldo y lavanda. En cábala corresponde a Hod (Sephirah 8, la Gloria/Esplendor). Hermes-Mercurio es el psychopompos (guía de almas), el patrón de alquimistas y magos.",
             "dia": "miércoles",
             "metal": "azogue (mercurio)",
             "color": "naranja / mezclado",
             "numero": "8",
             "angel_regente": "Rafael",
             "inteligencia": "Tiriel",
             "espiritu": "Tapthartharath",
             "sephirah": "Hod (8)",
             "fuente": "Agrippa, Lib. II cap. XXIX; Golden Dawn, 777; Cábala",
         }),

    dict(slug="planeta-venus", item_type="planet", name="Venus", planet="venus", element="agua",
         aliases=["Venus", "Afrodita", "Ishtar", "♀"],
         properties={
             "intenciones": ["amor", "belleza", "armonía", "arte", "placer", "atracción"],
             "notas": "La Estrella de la Mañana; rige el amor, la belleza, las artes y la conexión afectiva.",
             "estudio": "Venus rige los riñones, la piel, el tacto y las relaciones. Agrippa (Lib. II) le asigna el número 7, el cuadrado de 7×7, el día viernes, color verde/rosa, metal cobre, ángel Anael (o Haniel), inteligencia Hagiel y espíritu Kedemel. Sus hierbas incluyen rosa, verbena, tomillo, díctamo, mejorana y milenrama. En cábala corresponde a Netzach (Sephirah 7, la Victoria). Venus es el principio del deseo que mueve el cosmos — el 'motor' del amor platónico de Marsilio Ficino.",
             "dia": "viernes",
             "metal": "cobre",
             "color": "verde / rosa",
             "numero": "7",
             "angel_regente": "Anael",
             "inteligencia": "Hagiel",
             "espiritu": "Kedemel",
             "sephirah": "Netzach (7)",
             "fuente": "Agrippa, Lib. II cap. XXVIII; Golden Dawn, 777; Ficino, De Amore",
         }),

    dict(slug="planeta-marte", item_type="planet", name="Marte", planet="mars", element="fuego",
         aliases=["Mars", "Ares", "Nergal", "♂"],
         properties={
             "intenciones": ["fuerza", "coraje", "protección", "destierro", "conflicto", "acción"],
             "notas": "El guerrero del zodíaco; rige la voluntad de acción, la protección y la energía de destierro.",
             "estudio": "Marte rige la vesícula biliar, los músculos, la sangre y la energía física. Agrippa (Lib. II) le asigna el número 5, el cuadrado de 5×5, el día martes, color rojo, metal hierro, ángel Samael (o Camael), inteligencia Graphiel y espíritu Barzabel. Sus hierbas incluyen ruda, ajenjo, jengibre, ajo, albahaca y pimientos. En cábala corresponde a Geburah (Sephirah 5, la Severidad/Fuerza). Marte es el principio de delimitación y defensa — sin Marte no hay protección posible.",
             "dia": "martes",
             "metal": "hierro",
             "color": "rojo",
             "numero": "5",
             "angel_regente": "Samael",
             "inteligencia": "Graphiel",
             "espiritu": "Barzabel",
             "sephirah": "Geburah (5)",
             "fuente": "Agrippa, Lib. II cap. XXVII; Golden Dawn, 777; Cábala",
         }),

    dict(slug="planeta-jupiter", item_type="planet", name="Júpiter", planet="jupiter", element="aire",
         aliases=["Jupiter", "Zeus", "Marduk", "♃"],
         properties={
             "intenciones": ["expansión", "prosperidad", "sabiduría", "justicia", "suerte"],
             "notas": "El benéfico mayor; rige la expansión, la abundancia, el juicio justo y la buena fortuna.",
             "estudio": "Júpiter rige el hígado, las arterias, la sangre y el sistema de crecimiento. Agrippa (Lib. II) le asigna el número 4, el cuadrado de 4×4, el día jueves, color azul/púrpura, metal estaño, ángel Sachiel (o Tzadkiel), inteligencia Iophiel y espíritu Hismael. Sus hierbas incluyen salvia, hisopo, cedro, agrimonia y nuez moscada. En cábala corresponde a Chesed (Sephirah 4, la Misericordia). Júpiter es el principio de gracia y abundancia — el 'gran benéfico' de la astrología clásica.",
             "dia": "jueves",
             "metal": "estaño",
             "color": "azul / púrpura",
             "numero": "4",
             "angel_regente": "Sachiel",
             "inteligencia": "Iophiel",
             "espiritu": "Hismael",
             "sephirah": "Chesed (4)",
             "fuente": "Agrippa, Lib. II cap. XXVI; Golden Dawn, 777; Cábala",
         }),

    dict(slug="planeta-saturno", item_type="planet", name="Saturno", planet="saturn", element="tierra",
         aliases=["Saturn", "Cronos", "Ninurta", "♄"],
         properties={
             "intenciones": ["límites", "disciplina", "trabajo ctónico", "tiempo", "karma", "ancestros"],
             "notas": "El gran maestro y devorador; rige el tiempo, los límites, la muerte y la sabiduría de la edad.",
             "estudio": "Saturno rige el bazo, los huesos, los dientes, el oído y el sistema de envejecimiento. Agrippa (Lib. II) le asigna el número 3, el cuadrado de 3×3, el día sábado, color negro/índigo, metal plomo, ángel Cassiel (o Tzaphkiel), inteligencia Agiel y espíritu Zazel. Sus hierbas incluyen beleño, belladona, consuelda, tamarisco y asfódelo. En cábala corresponde a Binah (Sephirah 3, la Comprensión/Gran Madre). Saturno es el principio de forma y límite sin el cual ninguna manifestación es posible.",
             "dia": "sábado",
             "metal": "plomo",
             "color": "negro / índigo",
             "numero": "3",
             "angel_regente": "Cassiel",
             "inteligencia": "Agiel",
             "espiritu": "Zazel",
             "sephirah": "Binah (3)",
             "fuente": "Agrippa, Lib. II cap. XXII; Golden Dawn, 777; Cábala",
         }),
]

ANGELES: list[dict] = [
    dict(slug="arcangel-miguel", item_type="angel", name="Arcángel Miguel", planet="sun", element="fuego",
         aliases=["Michael", "Mikael", "מִיכָאֵל"],
         properties={
             "intenciones": ["protección", "justicia", "fuerza", "exorcismo", "liderazgo"],
             "notas": "El arcángel del Sol y del fuego; comandante de los ejércitos celestiales y vencedor de Lucifer.",
             "estudio": "Miguel (hebreo מִיכָאֵל, 'quién como Dios') es el arcángel regente del Sol en la tradición hermética. Agrippa (Lib. III) lo asigna al Sol. Aparece en Daniel 10:13, Judas 1:9 y Apocalipsis 12:7. En el sistema de los Siete Arcángeles Planetarios (tradición enóquica y cabalística) es el patrón del domingo. En el catolicismo es el patrón de los guerreros y la Iglesia militante. Su color es el dorado y el rojo de la armadura. Se invoca para protección, exorcismo y justicia divina. Corresponde a la Sephirah Tiphareth en la cábala.",
             "dia": "domingo",
             "sephirah": "Tiphareth (6)",
             "color": "dorado / rojo",
             "fuente": "Agrippa, Lib. III; Daniel 10:13; Apocalipsis 12:7; tradición cabalística",
         }),

    dict(slug="arcangel-gabriel", item_type="angel", name="Arcángel Gabriel", planet="moon", element="agua",
         aliases=["Gabriel", "Gavriel", "גַּבְרִיאֵל"],
         properties={
             "intenciones": ["revelación", "mensajes", "intuición", "sueños proféticos", "anunciación"],
             "notas": "El arcángel de la Luna y los mensajes divinos; anunció el nacimiento de Juan y de Jesús.",
             "estudio": "Gabriel (hebreo גַּבְרִיאֵל, 'Dios es mi fuerza') es el arcángel regente de la Luna. Agrippa (Lib. III) lo asigna a la Luna. Aparece en Daniel 8:16, Lucas 1:19 y en el Corán como el ángel que reveló a Mahoma. Es el mensajero de la revelación divina por excelencia. En magia lunar es el ángel de las visiones en sueños, de los mensajes a través del espejo o el agua, y de los ciclos femeninos. Su color es el plateado y el blanco. Corresponde a la Sephirah Yesod.",
             "dia": "lunes",
             "sephirah": "Yesod (9)",
             "color": "plateado / blanco",
             "fuente": "Agrippa, Lib. III; Lucas 1:19; tradición islámica (Jibril); Cábala",
         }),

    dict(slug="arcangel-rafael", item_type="angel", name="Arcángel Rafael", planet="mercury", element="aire",
         aliases=["Raphael", "רָפָאֵל"],
         properties={
             "intenciones": ["curación", "viaje", "comunicación", "ciencia médica", "protección del viajero"],
             "notas": "El arcángel de Mercurio y la curación; guía a Tobías en su viaje y cura la ceguera de su padre.",
             "estudio": "Rafael (hebreo רָפָאֵל, 'Dios sana') es el arcángel regente de Mercurio. Agrippa (Lib. III) lo asigna a Mercurio. Aparece en el Libro de Tobías (deuterocanónico) como guía del viaje y curador. En la tradición hermética es el patrón de la medicina, los viajeros y el conocimiento científico. Su color es el amarillo-naranja de Mercurio. Corresponde a la Sephirah Hod. En el LBRP (Lesser Banishing Ritual of the Pentagram) de la Golden Dawn se invoca en el este, dirección del aire.",
             "dia": "miércoles",
             "sephirah": "Hod (8)",
             "color": "amarillo / naranja",
             "fuente": "Agrippa, Lib. III; Libro de Tobías; Golden Dawn (LBRP); Cábala",
         }),

    dict(slug="arcangel-anael", item_type="angel", name="Arcángel Anael", planet="venus", element="agua",
         aliases=["Haniel", "Aniel", "אֲנִיאֵל"],
         properties={
             "intenciones": ["amor", "belleza", "armonía", "arte", "gracia", "relaciones"],
             "notas": "El arcángel de Venus y la gracia divina; preside el amor sagrado y la belleza espiritual.",
             "estudio": "Anael (también Haniel, 'gracia de Dios') es el arcángel regente de Venus. Agrippa (Lib. III) lo asigna a Venus. Aparece en el libro de Enoc y en las tradiciones angélicas judías medievales. Preside el viernes y los trabajos de amor, arte y reconciliación. Su color es el verde y el rosa venusinos. Corresponde a la Sephirah Netzach. Se invoca para bendecir relaciones, abrir el corazón cerrado y encontrar la belleza en lo cotidiano.",
             "dia": "viernes",
             "sephirah": "Netzach (7)",
             "color": "verde / rosa",
             "fuente": "Agrippa, Lib. III; Libro de Enoc (tradición); tradición cabalística",
         }),

    dict(slug="arcangel-samael", item_type="angel", name="Arcángel Samael", planet="mars", element="fuego",
         aliases=["Camael", "Chamuel", "Samael", "שַׂמָאֵל"],
         properties={
             "intenciones": ["fuerza", "protección guerrera", "justicia divina", "coraje", "destierro"],
             "notas": "El arcángel de Marte; ejecutor de la justicia divina y protector de los que luchan con rectitud.",
             "estudio": "Samael/Camael ('severidad de Dios' o 'el que ve a Dios') es el arcángel regente de Marte. Agrippa (Lib. III) lo asigna a Marte. En algunas tradiciones cabalísticas Samael es ambivalente (ángel y demonio); en la tradición hermética occidental (Golden Dawn) se usa el nombre Camael para el aspecto protector-marcial. Preside el martes. Corresponde a la Sephirah Geburah. Se invoca para protección física en situaciones de peligro real, para dar coraje y para ejecutar destierros con fuerza.",
             "dia": "martes",
             "sephirah": "Geburah (5)",
             "color": "rojo",
             "fuente": "Agrippa, Lib. III; Golden Dawn, 777; tradición cabalística (Geburah)",
         }),

    dict(slug="arcangel-sachiel", item_type="angel", name="Arcángel Sachiel", planet="jupiter", element="aire",
         aliases=["Tzadkiel", "Zadkiel", "Sachiel", "צַדְקִיאֵל"],
         properties={
             "intenciones": ["abundancia", "misericordia", "justicia", "expansión", "perdón"],
             "notas": "El arcángel de Júpiter; preside la misericordia divina, la abundancia y el perdón de deudas.",
             "estudio": "Sachiel (también Tzadkiel, 'justicia de Dios') es el arcángel regente de Júpiter. Agrippa (Lib. III) lo asigna a Júpiter. En la tradición cabalística es el ángel que detuvo la mano de Abraham en el Monte Moriah. Preside el jueves y los trabajos de prosperidad, expansión y misericordia. Corresponde a la Sephirah Chesed. Su color es el azul-púrpura jovial. Se invoca para atraer fortuna, para pedir misericordia en situaciones difíciles y para expandir proyectos.",
             "dia": "jueves",
             "sephirah": "Chesed (4)",
             "color": "azul / púrpura",
             "fuente": "Agrippa, Lib. III; tradición cabalística (Chesed); Golden Dawn, 777",
         }),

    dict(slug="arcangel-cassiel", item_type="angel", name="Arcángel Cassiel", planet="saturn", element="tierra",
         aliases=["Tzaphkiel", "Kafziel", "Cassiel", "צַפְקִיאֵל"],
         properties={
             "intenciones": ["tiempo", "karma", "soledad", "trabajo con ancestros", "silencio", "límites"],
             "notas": "El arcángel de Saturno; preside el tiempo, el karma, los ancestros y la contemplación solitaria.",
             "estudio": "Cassiel (también Tzaphkiel, 'contemplación de Dios') es el arcángel regente de Saturno. Agrippa (Lib. III) lo asigna a Saturno. Es el más silencioso y solitario de los arcángeles — no habla, solo observa y registra. Preside el sábado. Corresponde a la Sephirah Binah (Gran Madre, Comprensión). Se invoca para trabajos de largo plazo, para honrar a los ancestros, para comprender las consecuencias del karma y para encontrar paz en la soledad necesaria.",
             "dia": "sábado",
             "sephirah": "Binah (3)",
             "color": "negro / índigo",
             "fuente": "Agrippa, Lib. III; tradición cabalística (Binah); Golden Dawn, 777",
         }),
]

SIGNOS: list[dict] = [
    dict(slug="signo-aries", item_type="sign", name="Aries", planet="mars", element="fuego",
         aliases=["Aries", "El Carnero", "♈"],
         properties={
             "intenciones": ["inicio", "impulso", "coraje", "liderazgo"],
             "notas": "El primer signo; energía de comienzo puro, coraje e impulso hacia lo desconocido.",
             "estudio": "Aries (21 mar – 19 abr) es el signo cardinal de fuego, regido por Marte. En la teoría de los cuatro humores corresponde al temperamento colérico. Agrippa (Lib. II) lo vincula con la cabeza y el rostro. En la tradición hermética es el signo del equinoccio de primavera — el inicio del año mágico. La carta de Aries es la del guerrero-pionero que actúa antes de pensar. Hierbas de Aries incluyen el ajo, la ruda y el jengibre.",
             "modalidad": "cardinal",
             "cuerpo": "cabeza, rostro",
             "piedra": "diamante, cornalina",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias de signos)",
         }),

    dict(slug="signo-tauro", item_type="sign", name="Tauro", planet="venus", element="tierra",
         aliases=["Taurus", "El Toro", "♉"],
         properties={
             "intenciones": ["estabilidad", "abundancia", "sensualidad", "persistencia"],
             "notas": "El signo fijo de tierra; rige la materia, los sentidos y la acumulación de recursos.",
             "estudio": "Tauro (20 abr – 20 may) es el signo fijo de tierra, regido por Venus. Corresponde al cuello y la garganta. Agrippa (Lib. II) lo vincula con los bienes materiales y la construcción. La Venus exaltada de Tauro produce la expresión más sensorial y tenaz del principio venusino. Hierbas de Tauro incluyen la rosa, el tomillo y la verbena. Piedras: esmeralda, malaquita. En el año agrícola antiguo, Tauro correspondía a la siembra — momento de fijación de la semilla en la tierra.",
             "modalidad": "fijo",
             "cuerpo": "cuello, garganta",
             "piedra": "esmeralda, malaquita",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-géminis", item_type="sign", name="Géminis", planet="mercury", element="aire",
         aliases=["Gemini", "Los Gemelos", "♊"],
         properties={
             "intenciones": ["comunicación", "adaptabilidad", "aprendizaje", "dualidad"],
             "notas": "El signo mutable de aire; rige la mente dual, el intercambio y la conexión entre opuestos.",
             "estudio": "Géminis (21 may – 20 jun) es el signo mutable de aire, regido por Mercurio. Corresponde a los brazos, manos, pulmones y sistema nervioso. Agrippa (Lib. II) lo asocia con el intercambio y la duplicidad. Los Dioscuros (Cástor y Pólux) son su símbolo mítico — dos naturezas, mortal e inmortal. Hierbas de Géminis incluyen la lavanda, el eneldo y la menta. Es el signo del mensajero, el comerciante y el filósofo dialéctico.",
             "modalidad": "mutable",
             "cuerpo": "brazos, manos, pulmones",
             "piedra": "aguamarina, citrino",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-cáncer", item_type="sign", name="Cáncer", planet="moon", element="agua",
         aliases=["Cancer", "El Cangrejo", "♋"],
         properties={
             "intenciones": ["hogar", "memoria", "nutrición", "ciclos emocionales"],
             "notas": "El signo cardinal de agua; rige el hogar, la madre, la memoria ancestral y los ciclos lunares.",
             "estudio": "Cáncer (21 jun – 22 jul) es el signo cardinal de agua, regido por la Luna. Corresponde al pecho, estómago e intestinos. El solsticio de verano (inicio de Cáncer) fue siempre un momento de máxima potencia lunar y mágica. Agrippa lo vincula con los fluidos, la gestación y la memoria ancestral. Hierbas de Cáncer incluyen la artemisa, el nenúfar y el sauce. Es el signo de la sacerdotisa, la partera y el guardián de la tradición oral.",
             "modalidad": "cardinal",
             "cuerpo": "pecho, estómago",
             "piedra": "piedra de luna, perla",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-leo", item_type="sign", name="Leo", planet="sun", element="fuego",
         aliases=["Leo", "El León", "♌"],
         properties={
             "intenciones": ["poder", "creatividad", "generosidad", "presencia", "soberanía"],
             "notas": "El signo fijo de fuego; rige el corazón, la creatividad y el poder soberano del yo consciente.",
             "estudio": "Leo (23 jul – 22 ago) es el signo fijo de fuego, regido por el Sol. Corresponde al corazón y la columna vertebral. Agrippa lo vincula con el poder real y la vitalidad. El Sol en Leo es el Sol en máxima expresión de su naturaleza — el rey en su trono. Hierbas de Leo incluyen el laurel, el girasol y la caléndula. Piedras: rubí, ojo de tigre. Leo es el signo del artista, el líder y el aristócrata de espíritu.",
             "modalidad": "fijo",
             "cuerpo": "corazón, columna",
             "piedra": "rubí, ojo de tigre",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-virgo", item_type="sign", name="Virgo", planet="mercury", element="tierra",
         aliases=["Virgo", "La Virgen", "♍"],
         properties={
             "intenciones": ["discernimiento", "salud", "servicio", "análisis", "pureza"],
             "notas": "El signo mutable de tierra; rige el análisis, la salud, el servicio y la artesanía detallada.",
             "estudio": "Virgo (23 ago – 22 sep) es el signo mutable de tierra, regido por Mercurio. Corresponde al intestino delgado y el sistema digestivo analítico. Agrippa lo vincula con la herbolaria y las artes de curación. La imagen de la Virgen con espiga de trigo (Deméter/Ceres) marca el tiempo de la cosecha. Hierbas de Virgo incluyen el eneldo, la manzanilla y el hinojo. Virgo es el signo del curandero, el alquimista y el artesano perfeccionista.",
             "modalidad": "mutable",
             "cuerpo": "intestinos, sistema digestivo",
             "piedra": "peridoto, jaspe",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-libra", item_type="sign", name="Libra", planet="venus", element="aire",
         aliases=["Libra", "La Balanza", "♎"],
         properties={
             "intenciones": ["equilibrio", "justicia", "asociación", "armonía", "belleza"],
             "notas": "El signo cardinal de aire; rige la justicia, las asociaciones y el equilibrio entre opuestos.",
             "estudio": "Libra (23 sep – 22 oct) es el signo cardinal de aire, regido por Venus. Corresponde a los riñones, la piel y el equilibrio homeostático. El equinoccio de otoño inicia Libra — el punto de equilibrio perfecto entre luz y oscuridad. Agrippa lo asocia con las artes, la diplomacia y la estética. Piedras: lapislázuli, zafiro. Hierbas: rosa, verbena. Libra es el signo del árbitro, el artista y el diplomático.",
             "modalidad": "cardinal",
             "cuerpo": "riñones, piel",
             "piedra": "lapislázuli, zafiro",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-escorpio", item_type="sign", name="Escorpio", planet="mars", element="agua",
         aliases=["Scorpio", "El Escorpión", "♏"],
         properties={
             "intenciones": ["transformación", "profundidad", "muerte y renacimiento", "magia sexual"],
             "notas": "El signo fijo de agua; rige la transformación, la muerte simbólica y la regeneración profunda.",
             "estudio": "Escorpio (23 oct – 21 nov) es el signo fijo de agua, regido por Marte (y Plutón en astrología moderna). Corresponde a los órganos reproductores, la vejiga y el colon. Agrippa lo vincula con los venenos, la magia sexual y las transformaciones irreversibles. Es el signo de los alquimistas, los chamanes y los detectives del alma. Hierbas: albahaca, mandrágora, galangal. Piedras: obsidiana, granate.",
             "modalidad": "fijo",
             "cuerpo": "órganos reproductores, colon",
             "piedra": "obsidiana, granate",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-sagitario", item_type="sign", name="Sagitario", planet="jupiter", element="fuego",
         aliases=["Sagittarius", "El Centauro", "♐"],
         properties={
             "intenciones": ["expansión", "filosofía", "viaje", "fe", "sabiduría superior"],
             "notas": "El signo mutable de fuego; rige el viaje hacia la verdad, la filosofía y la expansión del horizonte.",
             "estudio": "Sagitario (22 nov – 21 dic) es el signo mutable de fuego, regido por Júpiter. Corresponde a los muslos, caderas y nervio ciático. Agrippa lo asocia con la filosofía, la religión comparada y la búsqueda de sentido. El Centauro Quirón — maestro de héroes, sanador de dioses — es su símbolo mítico. Hierbas: salvia, hisopo, cedro. Piedras: turquesa, sodalita. Sagitario es el signo del filósofo, el explorador y el profeta.",
             "modalidad": "mutable",
             "cuerpo": "muslos, caderas",
             "piedra": "turquesa, sodalita",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-capricornio", item_type="sign", name="Capricornio", planet="saturn", element="tierra",
         aliases=["Capricorn", "El Cabra-Pez", "♑"],
         properties={
             "intenciones": ["ambición", "disciplina", "estructura", "logro a largo plazo"],
             "notas": "El signo cardinal de tierra; rige la disciplina, la estructura institucional y el logro paciente.",
             "estudio": "Capricornio (22 dic – 19 ene) es el signo cardinal de tierra, regido por Saturno. Corresponde a las rodillas, los huesos y los dientes. El solsticio de invierno (inicio de Capricornio) es el punto de máxima oscuridad — el Sol renaciendo en lo más profundo de Saturno. Agrippa lo asocia con la ambición política, la arquitectura y las instituciones duraderas. Hierbas: consuelda, beleño. Piedras: cuarzo ahumado, ónix negro.",
             "modalidad": "cardinal",
             "cuerpo": "rodillas, huesos",
             "piedra": "cuarzo ahumado, ónix negro",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-acuario", item_type="sign", name="Acuario", planet="saturn", element="aire",
         aliases=["Aquarius", "El Aguador", "♒"],
         properties={
             "intenciones": ["innovación", "comunidad", "libertad", "visión de futuro"],
             "notas": "El signo fijo de aire; rige la visión colectiva, la innovación y la conciencia de grupo.",
             "estudio": "Acuario (20 ene – 18 feb) es el signo fijo de aire, regido por Saturno (y Urano en astrología moderna). Corresponde a los tobillos, pantorrillas y circulación venosa. Agrippa lo asocia con la astrología, la filosofía política y las utopías. El portador de agua vierte el conocimiento para todos — imagen del reformador y el visionario. Hierbas: lavanda, helecho. El 'tiempo de Acuario' en la tradición esotérica del s. XX refiere a la era precesional actual.",
             "modalidad": "fijo",
             "cuerpo": "tobillos, circulación venosa",
             "piedra": "amatista, aguamarina",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),

    dict(slug="signo-piscis", item_type="sign", name="Piscis", planet="jupiter", element="agua",
         aliases=["Pisces", "Los Peces", "♓"],
         properties={
             "intenciones": ["compasión", "disolver límites", "misticismo", "sacrificio", "sueños"],
             "notas": "El signo mutable de agua; rige la disolución del ego, la compasión universal y el misticismo.",
             "estudio": "Piscis (19 feb – 20 mar) es el signo mutable de agua, regido por Júpiter (y Neptuno en astrología moderna). Corresponde a los pies y el sistema linfático. Es el último signo — el que disuelve todas las formas para preparar el nuevo comienzo de Aries. Agrippa lo asocia con los hospitales, los monasterios y los estados contemplativos. Hierbas: artemisa, valeriana, sauce. Piedras: piedra de luna, amatista. Piscis es el signo del místico, el artista y el mártir.",
             "modalidad": "mutable",
             "cuerpo": "pies, sistema linfático",
             "piedra": "piedra de luna, amatista",
             "fuente": "Agrippa, Lib. II; Culpeper (regencias)",
         }),
]
